version: "3.5"

services:
  sensor:
    build:
      context: sensor
      target: sensor
    depends_on:
      - compile
      - mosquitto

  motion_processor:
    build:
      context: motion_processor
      target: motion_processor
    depends_on:
      - compile
      - mosquitto

  telegram_bot_controller:
    build:
      context: telegram_bot_controller
      target: telegram_bot_controller
    secrets:
      - telegram_bot_token
    depends_on:
      - compile
      - mosquitto

  compile:
    build:
      context: .
      dockerfile: compile/Dockerfile
      target: builder
    volumes:
      - ./bin:/go/bin
    command: ""

  mosquitto:
    build: mosquitto
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

volumes:
  mosquitto-data:
secrets:
  telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt 

