version: "3.5"

services:
   compile-arm:
    build:
      context: .
      dockerfile: compile/Dockerfile
      target: builder
    volumes:
      - ./bin:/go/bin
    environment:
      - GOOS=linux
      - GOARCH=arm 
      - GOARM=5
  
